### ISSUE TITLE
FieldDefinitions cop doesn't work on module interfaces

### ISSUE THREAD

**Issue by eapache-opslevel** [DmitryTsepelev/rubocop-graphql#110]
```ruby
# frozen_string_literal: true

module Types
  module SomeInterfaceType
    include Types::BaseInterface

    field :field_one, String, null: false
    field :field_two, String, null: true

    def field_one
      # do something
    end

    def field_two
      # do something else
    end
  end
end
```

with
```
GraphQL/FieldDefinitions:
  Enabled: true
  EnforcedStyle: define_resolver_after_definition
```

Produces no warnings or diffs, presumably because it's only looking for classes that inherit from `GraphQL::Schema::Object`, and not modules?

cc @ravangen @toneymathews I think you've been looking at this cop recently, not sure if you have any insight? Also, hi, hope everything is good!

cc @exterm

**Comment by DmitryTsepelev** [comment]
Hey @eapache-opslevel!

Fixed in https://github.com/DmitryTsepelev/rubocop-graphql/pull/112, the problem was that this cop was not considered modules at all. Please let me know if it does not help.

**Comment by eapache-opslevel** [comment]
Thanks for the quick response. Our config uses `define_resolver_after_definition`, so the PR doesn't help since it only runs if the style is `group_definitions`.
