### ISSUE TITLE
NotAuthorizedNodeType fails when authorized? is defined in base class

### ISSUE THREAD

**Issue by grjones** [DmitryTsepelev/rubocop-graphql#116]
For implementations that use a more generic approach defined in a base class `authorized?`, this new cop fails. Any objection to loosening this up a bit to allow for base class implementation?

Original PR: https://github.com/DmitryTsepelev/rubocop-graphql/pull/115

**Comment by DmitryTsepelev** [comment]
Hey! Well, Rubocop has issues with checking other classes while inspecting a specific file, so I'd suggest the following:

1. add a config option for `SafeBaseClasses: []`
2. change a cop to check if class is implementing `authorized?` or inherits from one of those base ones

WDYT?

**Comment by grjones** [comment]
@DmitryTsepelev Thanks so much for the quick response. I didn't realize Rubocop has trouble in that way. I don't think I'm knowledgeable enough with Rubocop to give an opinion, but if that seems like the best way to you, I believe you. 😄

**Comment by grjones** [comment]
Thank you so much 😊
