### ISSUE TITLE
False positives for GraphQL/MaxComplexitySchema and GraphQL/MaxDepthSchema

### ISSUE THREAD

**Issue by nerixim** [DmitryTsepelev/rubocop-graphql#117]
Hi, thank you for your work 👍 

I've just updated to 1.0 and got some offences with new cops.
I've read the [docs](https://graphql-ruby.org/queries/complexity_and_depth) and added query analyzers for my schema class. After deciding on my max complexity and max depth, I've set them on my schema class but the offences persist for the analyzer classes.

```ruby
class ComplexityAnalyzer < GraphQL::Analysis::AST::QueryComplexity
  def result
    query.context[:_complexity] = super
  end
end

class DepthAnalyzer < GraphQL::Analysis::AST::QueryDepth
  def result
    query.context[:_depth] = super
  end
end

class MySchema < GraphQL::Schema
  query_analyzer ComplexityAnalyzer
  query_analyzer DepthAnalyzer

  mutation(Types::MutationType)
  query(Types::QueryType)

  max_complexity 100
  max_depth 10
end
```

**Comment by DmitryTsepelev** [comment]
Hey @nerixim! Do I understand correctly that all these classes are defined in the `my_schema.rb`? I'd suggest to move them to separate files, as far as I rememver [zeitwerk](https://github.com/fxn/zeitwerk) asks to do that too

**Comment by nerixim** [comment]
Thanks, autoloading was the case 👍
