### ISSUE TITLE
GraphQL/NotAuthorizedNodeType incompatible with Style/ClassMethodsDefinitions

### ISSUE THREAD

**Issue by rporrasluc** [DmitryTsepelev/rubocop-graphql#119]
It seems that the new cop fails if the class method `authorized?` is defined inside a `class << self` block.

I have created [this PR](https://github.com/DmitryTsepelev/rubocop-graphql/pull/118) with a failing test that I think should pass.

Thanks!

**Comment by DmitryTsepelev** [comment]
Hey @rporrasluc! Thanks for the test, I'll try to fix the issue soon 🙂
