### ISSUE TITLE
FieldDefinitions cop doesn't work on modules with `define_resolver_after_definition`

### ISSUE THREAD

**Issue by eapache-opslevel** [DmitryTsepelev/rubocop-graphql#123]
This is a semi-duplicate of #110 because that was closed and I do not have permissions to re-open it.

The fix for that issue did fix modules when the style is `group_definitions`, but our rubocop config uses the style `define_resolver_after_definition`, which still doesn't run on modules.

```ruby
# frozen_string_literal: true

module Types
  module SomeInterfaceType
    include Types::BaseInterface

    field :field_one, String, null: false
    field :field_two, String, null: true

    def field_one
      # do something
    end

    def field_two
      # do something else
    end
  end
end
```

with
```
GraphQL/FieldDefinitions:
  Enabled: true
  EnforcedStyle: define_resolver_after_definition
```

Produces no warnings or diffs. (Note the `EnforcedStyle`).

cc @exterm again

**Comment by DmitryTsepelev** [comment]
Hey @eapache-opslevel, are you on the latest version? I tried to add a test for that and it seems to work https://github.com/DmitryTsepelev/rubocop-graphql/blob/master/spec/rubocop/cop/graphql/field_definitions_spec.rb#L615
