### ISSUE TITLE
MaxComplexitySchema and MaxDepthSchema leak into subclasses

### ISSUE THREAD

**Issue by xxx** [DmitryTsepelev/rubocop-graphql#125]
Heya, thank you for making this gem.

We have some custom error classes defined locally within our gql schema, and these lints are popping for those classes as well.

```ruby
class MySchema < GraphQL::Schema
  max_complexity 100
  max_depth 10

  class AccountDisabledError < GraphQL::ExecutionError; end # still complains about this, even though they're set in the schema
end
```

**Comment by DmitryTsepelev** [comment]
Hey hey! Attached a PR with a fix, will add into the upcoming release 🙂
