### ISSUE TITLE
OrderedFields configurable option to put id field first

### ISSUE THREAD

**Issue by TSMMark** [DmitryTsepelev/rubocop-graphql#129]
`id` is of course a special field, and our codebase has a convention to place the `id` field first above all other fields.

Would you accept a configuration such as `IdFieldFirst: True/False` to enforce + autocorrect id to be first "alphabetically"?

`OrderedArguments` could also support the same option.

Thanks!

**Comment by DmitryTsepelev** [comment]
Hi @TSMMark! Definitely, sounds reasonable! I wonder if we want to generalize it to something like:

```
FieldsOnTop:
  - id
  - something_else
```

**Comment by TSMMark** [comment]
That could work, however I think if we're going to generalize and support more customizability we could consider following a similar approach to the eslint plugin react `sort-comp` configuration: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/sort-comp.md

It can be configured like this:

```
"react/sort-comp": [1, {
  order: [
    'static-methods',
    'lifecycle',
    '/^on.+$/',
    'render',
    'everything-else'
  ]
}]
```

This allows for more complete flexibility. Regex patterns, placing some fields at the end of the list, etc.

So for rubocop-graphql we could do something like this for example:

```yaml
FieldsOrder:
  - id
  - '/^id_.*/' # any id-related fields
  - 'everything-else'
  - '/^.*_at/' # create_at and update_at at the bottom
```

What do you think?

**Comment by TSMMark** [comment]
@DmitryTsepelev If you like the direction of this or have a better idea, lmk!
