### ISSUE TITLE
`GraphQL/*Description`s autocorrection idea

### ISSUE THREAD

**Issue by RasimKhusaenov** [DmitryTsepelev/rubocop-graphql#138]
The rules for filling out GraphQL descriptions are a bit annoying, because they make you do monotonous work. I was thinking that maybe we could set a file with default values for specific characters for the cop to use for autocorrect? What I mean: we have some field without description:
```ruby
field :company_id, Types::CompanyType
```
And some file:
```yaml
descriptions:
  fields:
    company_id: ID of company
```
I run:
```bash
bin/rubocop -A
```
And it autocorrects it to:
```ruby
field :company_id, Types::CompanyType, description: 'ID of company.'
```
Can this be accomplished with a rubocop?

**Comment by DmitryTsepelev** [comment]
Hey! Yes, it should be possible using the https://docs.rubocop.org/rubocop/usage/auto_correct.html, but sounds like it's easier to just disable the cop if it does not bring a lot of value 🙂

**Comment by DmitryTsepelev** [comment]
Rubocop is a linter, not a codegen tool 🙂 I'd rather do something like this:

1. disable this particular cop in the project
2. add a [field extenstion](https://graphql-ruby.org/type_definitions/field_extensions.html) to just add that boring description if it's missing
