### ISSUE TITLE
Misleading documentation in unnecessary_argument_camelize rule

### ISSUE THREAD

**Issue by letiesperon** [DmitryTsepelev/rubocop-graphql#139]
The [unnecessary_argument_camelize](https://github.com/DmitryTsepelev/rubocop-graphql/blob/master/lib/rubocop/cop/graphql/unnecessary_argument_camelize.rb) rule doc says:

```
      #   # good
      #
      #   class UserType < BaseType
      #     argument :filter, String, required: false, camelize: false
      #   end
      #
      #  # bad
      #
      #   class UserType < BaseType
      #     argument :filter, String, required: false
      #   end
````

It should be the other way around right?
Unless I'm missing something
I can fix it if it's the case

**Comment by DmitryTsepelev** [comment]
Hey @letiesperon! Yes, that was a mistake, I've updated the doc, thank you for catching that 🙂
