### ISSUE TITLE
NotAuthorizedNodeType when using pundit

### ISSUE THREAD

**Issue by gagalago** [DmitryTsepelev/rubocop-graphql#140]
the linter is complaining about `NotAuthorizedNodeType` even when we use the [pundit integration](https://graphql-ruby.org/authorization/pundit_integration.html). it should see that we  are doing the authorization through pundit and so be silent for the type doing authorization through pundit.

```ruby
module Types
  class UserType < Types::Base::Object
    description "User personal data information"

    implements GraphQL::Types::Relay::Node
    global_id_field :id
    pundit_policy_class UserPolicy
    pundit_role :show
  end
end
```

**Comment by DmitryTsepelev** [comment]
Hey! Good catch, I guess we could add it to the cop 🙂
