### ISSUE TITLE
Add cop: force alphabetical order of arguments

### ISSUE THREAD

**Issue by DmitryTsepelev** [DmitryTsepelev/rubocop-graphql#16]
Check out OrderFields [PR](https://github.com/DmitryTsepelev/rubocop-graphql/pull/25) as an example

**Comment by kiskoza** [comment]
We should keep this issue open, #25 added only an OrderedFields cop, but we should have an OrderedArguments cop too

**Comment by DmitryTsepelev** [comment]
Good point, updated the issue
