### ISSUE TITLE
GraphQL/UnusedArgument false positive

### ISSUE THREAD

**Issue by jaydorsey** [DmitryTsepelev/rubocop-graphql#167]
I have noticed we have mutations with an `id` argument, and a resolver defined like this:

```
    argument :id, ID, required: true,
      loads: Types::Foo,
      pundit_role: :delete,
      description: 'UUID of the foo.'

    def load_id(id)
      Foo.find_by!(uuid: id)
    end

    def resolve(id:)
```

Every single one of them has a `GraphQL/UnusedArgument` rubocop error shown on the `resolve` line, but the output message is strangely formatted because it doesn't say what argument/name is missing

![image](https://github.com/user-attachments/assets/23bc0398-72fc-4810-9d5a-08a045c19d90)

I think this is a bug/false positive; if we remove the `id` argument it's fine (but we need that argument). I've also noticed if we have 2 arguments, and 1 of them is `id`, it fails because of the `id` argument.

I took at look at the code and I don't quite understand why it's broken, but it's related to this line/snippet here:

     declared_args.map(&method(:arg_name)).uniq

That piece of code returns a string: `GraphQL/UnusedArgument`

I'll try and loop back on this with at least a spec condition that fails but happy to have some extra eyes on it for a solution.

Thanks!

**Comment by DmitryTsepelev** [comment]
@jaydorsey thanks for the report, fixed in https://github.com/DmitryTsepelev/rubocop-graphql/pull/168 🙂

**Comment by jaydorsey** [comment]
Confirmed that this fixed it. Thank you!
