### ISSUE TITLE
Explicit opt out of descriptions

### ISSUE THREAD

**Issue by bessey** [DmitryTsepelev/rubocop-graphql#28]
Hi there, I am just getting started with this library, and definitely open to contributing this myself, but first thought I would see what you thought of the idea.

I think, sometimes, things do not need documentation. I would say the field `User.firstName`, the object `Query`, and the argument `Query.fetchAccount(id: ID!)` all gain little to nothing from being described.

I have found that the argument cop is appeased with a `argument :id, ..., description: nil`, but not `description: false`. Neither seems to work for object descriptions.

What do you think of allowing explicit opt out on a case by case basis via:
```ruby
class QueryType
  description false
  field :account, AccountType, description: false do
    argument :id, ID, description: false, required: true
  end
end
```

This is similar to how Elixir's Hexdocs handles module docs, and is a fair bit more concise than `#rubocop:disable GraphQL/XXXXError` all over the place

I have tested and GraphQL Ruby appears to be fine with these false values

**Comment by DmitryTsepelev** [comment]
Hi @bessey! I feel like using false might be error prone, since one day `graphql-ruby` may change the behavior and give `description: false` a new meaning. I believe `rubocop:disable` is a tool designed to solve such cases 🙂I'd rather disable it completely (in the rubocop config) if you don't need descriptions most of the time (to be honest, I do have it disabled in my current project, because API is pretty straightforward)

**Comment by bessey** [comment]
That's a fair concern. Given the graphql spec doesn't leave any room for a
description to be anything other than null or a String, it seems unlikely
that false will ever represent something else to me, but perhaps we could
reach out to rmosolgo and seek some assurance that there's nothing planned.

For now I will see how far we get just disabling some checks the rubocop
way. Thanks for the swift response, feel free to close out for now.

Matt

**Comment by DmitryTsepelev** [comment]
Great! By the way, if you have any ideas of the cops to add—I'm open to suggestions.
