### ISSUE TITLE
RuboCop: Missing field description [GraphQL/FieldDescription] with description method

### ISSUE THREAD

**Issue by itay-grudev** [DmitryTsepelev/rubocop-graphql#41]
When a field definition gets too long I use the method form of the description parameter, like so:

```ruby
  field :update_user, Types::UserType, null: true, mutation: Mutation::UserMutation do
    description 'Update user'
    argument :id, Integer, required: true, description: 'User ID'
  end
 ```
 
But this triggers the following error:
```txt
RuboCop: Missing field description [GraphQL/FieldDescription]
```

I know you have a `find_description_method(@nodes)` that can be used inside the cop to check whether it's set as a method, but I am not competent enough with Rubocop for a PR.

**Comment by DmitryTsepelev** [comment]
Hi @itay-grudev! Please let me know if you decide to fix this behavior or I'll eventually fix it 🙂Thanks for the report!
