### ISSUE TITLE
[GraphQL/ObjectDescription] on QueryContext

### ISSUE THREAD

**Issue by itay-grudev** [DmitryTsepelev/rubocop-graphql#42]
The `QueryContext < GraphQL::Query::Context` class located in `app/graphql/query_context.rb` should be ignored by default against the `GraphQL/ObjectDescription` rule.

**Comment by DmitryTsepelev** [comment]
Hi @itay-grudev! May I ask you to add it [here](https://github.com/DmitryTsepelev/rubocop-graphql/blob/master/config/default.yml#L80) and make a PR?
