### ISSUE TITLE
[GraphQL/FieldHashKey] incorrectly triggers for array access

### ISSUE THREAD

**Issue by aaronfrary** [DmitryTsepelev/rubocop-graphql#43]
The following definition results in the correctable offense `GraphQL/FieldHashKey: Use hash_key: 0` :

```rb
class ExampleType
  field :example, null: false

  def example
    object[0]
  end
end
```

Changing this to
```rb
  field :example, null: false, hash_key: 0
```
as suggested doesn't work, leading instead to a `NoMethodError: undefined method 'to_sym' for 0:Integer`.

I'm not sure if there's a better way to implement this that the cop could suggest instead, or if it'd be better for it just not to trigger in this case.

**Comment by DmitryTsepelev** [comment]
Hi @aaronfrary, thanks for the report!

I think that this is a false positive and we should teach cop how to skip such classes. Looks like we can take a key [here](https://github.com/DmitryTsepelev/rubocop-graphql/blob/master/lib/rubocop/cop/graphql/field_hash_key.rb#L50) and make sure it's not an Integer.

Do you want to try to implement it? 🙂

**Comment by aaronfrary** [comment]
Sure I can give it a go. I should have some time to work on it later today 🙂
