### ISSUE TITLE
Duplicates cause infinite loop in GraphQL/OrderedArguments and GraphQL/OrderedFields

### ISSUE THREAD

**Issue by justisb** [DmitryTsepelev/rubocop-graphql#49]
Currently if there is a duplicate argument defined, it causes an infinite loop when processing `GraphQL/OrderedArguments`, and the same for fields and `GraphQL/OrderedFields`.

Obviously this is a problem of its own in our schema and we were able to find the duplicates pretty quickly, but it likely shouldn't cause an infinite loop.

Perhaps duplicated field/argument definitions could be their own cops.

**Comment by DmitryTsepelev** [comment]
Hi @justisb! Thank you for the report—eventually I'll fix this bug, please let me know if you want to try to implement that 🙂

**Comment by justisb** [comment]
PR #50 submitted for review.
