### ISSUE TITLE
GraphQL/ObjectDescription when using constants

### ISSUE THREAD

**Issue by nevesenin** [DmitryTsepelev/rubocop-graphql#51]
Hi!

I use a constant as a description value as I try to be more DRY in case I have the same description for a type, field and argument. But GraphQL/ObjectDescription complains when using a constant like this:
```
class SomeType < BaseType
  description DESCRIPTION_CONSTANT
end
```

**Comment by DmitryTsepelev** [comment]
Hi @nevesenin! Good catch! Do you want to make an attempt to fix it? 🙂

**Comment by nevesenin** [comment]
Hi @DmitryTsepelev! I tried. ;)

**Comment by nevesenin** [comment]
Thanks a lot!
