### ISSUE TITLE
GraphQL/UnusedArgument false positive on optional arguments.

### ISSUE THREAD

**Issue by MrJoy** [DmitryTsepelev/rubocop-graphql#62]
```ruby
class Mutations::DoTheThng < Mutations::BaseMutation
  argument :foo,  String,    required: true
  argument :bar,  String,    required: true
  argument :baz, Boolean, required: false

  def resolve(foo:, bar:, baz: false)
    # ...
  end
end
```

Code such as the above produces the error:

```
GraphQL/UnusedArgument: Argument remember_me: should be listed in the resolve signature.
```

Using the auto-correct feature leads to the resolve method being changed to:

```ruby
  def resolve(foo:, bar:, baz: false, baz:)
```

**Comment by DmitryTsepelev** [comment]
Good catch! Russians are on holiday until the end of the week, so I'm not sure I'll be able to ship earlier, but PRs are welcome 🙂

**Comment by MrJoy** [comment]
Unfortunately, this is a bit beyond my ken, or I would have submitted one.  My apologies.

**Comment by nvasilevski** [comment]
I have a PR to address this - https://github.com/DmitryTsepelev/rubocop-graphql/pull/66
