### ISSUE TITLE
GraphQL/UnusedArgument false positives for auto-loading arguments

### ISSUE THREAD

**Issue by justisb** [DmitryTsepelev/rubocop-graphql#64]
For mutation classes, you can specify `loads:` and `as:` options to its arguments to automatically load an object by its ID, and then alias the argument name sent to the `resolve` method:
https://graphql-ruby.org/mutations/mutation_classes#auto-loading-arguments

Example from the docs:
```
class Mutations::AddStar < Mutations::BaseMutation
  argument :post_id, ID, loads: Types::Post, as: :something

  field :post, Types::Post

  def resolve(something:)
    something.star

    {
      post: something
    }
  end
end
```

Currently this example results in an incorrect `GraphQL/UnusedArgument: Argument post_id: should be listed in the resolve signature` rule violation.

The same error also occurs when `as` is not specified, and the default auto-loaded `post` argument is used.

Example from the docs:
```
class Mutations::AddStar < Mutations::BaseMutation
  argument :post_id, ID, loads: Types::Post

  field :post, Types::Post

  def resolve(post:)
    post.star

    {
      post: post,
    }
  end
end
```

**Comment by Tao-Galasse** [comment]
Bumped into the same error today.

As @justisb mentioned, it also happens when declaring `argument :foobar_id, ID, loads: Types::Foobar` and writing your resolve method with the parameter like this `def resolve(foobar:)`.

Follow up this issue ! :)

**Comment by DmitryTsepelev** [comment]
Good catch! Russians are on holiday until the end of the week, so I'm not sure I'll be able to ship earlier, but PRs are welcome  🙂

**Comment by aishek** [comment]
Oh, sorry for this. Fixed it in PR mentioned above
