### ISSUE TITLE
`GraphQL/UnusedArgument` should respect ruby `...`

### ISSUE THREAD

**Issue by biow0lf** [DmitryTsepelev/rubocop-graphql#73]
Hello,

rubocop-graphql should respect ruby `...` (shorthand syntax for forwarding arguments to a method).

Example code:

```ruby
def resolve(...)
  Forms::UpdateUserForm.new(context, ...)
end
```

**Comment by DmitryTsepelev** [comment]
Good point! Do you want to try to implement this? 🙂

**Comment by nipe0324** [comment]
I try to fix this. #79
